### ISSUE TITLE
建议添加 umd 格式作为返回

### ISSUE THREAD

**Issue by darkty2009** [EleanorMao/FlexoCalendar.js#1]
就像这样：

```
(function(root, factory) {
    if(typeof define === 'function' && define.amd) {
        define(factory);
    }
    else if(typeof exports === 'object') {
        module.exports = factory();
    }
    else {
        root.baseline = factory();
    }
})(this, function() {

});
```

这样可以让你的组件，在多种环境和模块化框架下都能使用

**Comment by EleanorMao** [comment]
哇(?o?;; 谢谢你的指导

发自我的 iPhone

在 2016年2月9日，04:38，SimpleLee <notifications@github.com<mailto:notifications@github.com>> 写道：

就像这样：

(function(root, factory) {
    if(typeof define === 'function' && defineamd) {
        define(factory);
    }
    else if(typeof exports === 'object') {
        moduleexports = factory();
    }
    else {
        rootbaseline = factory();
    }
})(this, function() {

});

这样可以让你的组件，在多种环境和模块化框架下都能使用

―

**Comment by EleanorMao** [comment]
谢谢你，我要关闭它了
